import { Sidebar } from "../components/sidebar";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="grid grid-cols-4 xl:grid-cols-5 min-h-screen">
          <Sidebar />
          <main className="col-span-3 xl:col-span-4">{children}</main>
        </div>
      </body>
    </html>
  );
}
